<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AppInfo</AssemblyName>
    <Product>AppInfo</Product>
    <Description>Collect, display and optionally save information about the host application during startup.</Description>
    <RootNamespace>AppInformation</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>AppInfo</PackageId>
    <Title>AppInfo</Title>
    <PackageTags>app info logging manifest</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>For a full changelog, please visit https://github.com/Reyhn3/AppInfo/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/Reyhn3/AppInfo</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/Reyhn3/AppInfo/blob/main/LICENSE</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/Reyhn3/AppInfo</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
