<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>custom</AssemblyName>
    <Product>AppInfo Demo - Custom</Product>
    <Description>Demonstrates the custom usage of AppInfo</Description>
    <RootNamespace>Custom</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppInfo\AppInfo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
      <DependentUpon>Dockerfile</DependentUpon>
    </Content>
  </ItemGroup>

</Project>
