<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>fluent</AssemblyName>
    <Product>AppInfo Demo - Fluent</Product>
    <Description>Demonstrates different ways to use the fluent syntax with AppInfo</Description>
    <RootNamespace>Fluent</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppInfo\AppInfo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>
