<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>basic</AssemblyName>
    <Product>AppInfo Demo - Basic</Product>
    <Description>Demonstrates the basic usage of AppInfo</Description>
    <RootNamespace>Basic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppInfo\AppInfo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>
