name: Publish NuGet


on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: '0.0.0-pre-0'
        description: "Version to publish"
      dry-run:
        required: true
        type: boolean
        default: true
        description: "Dry run (doesn't actually publish anything)"


jobs:
#  debug:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v7
#
#      - name: Version
#        run: echo "vars ${{ vars.VERSION }} env ${{ env.VERSION }} input ${{ github.event.inputs.version }}"
#
#      - name: List
#        run: ls -alR
#
#  build:
#    name: Build and Test
#    uses: ./.github/workflows/ci.yml
#    with:
#      version: ${{ github.event.inputs.version }}

  zip:
    name: Zip Source Code
#    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

#      - name: Zip Source Code
#        run: |
#          mkdir source
#          zip -r source/AppInfo-${{ github.event.inputs.version }}-source.zip .

      - name: Upload source code to artifacts
        uses: actions/upload-artifact@v4
        with:
#          name: AppInfo-${{ github.event.inputs.version }}-source.zip
#          path: source/
          name: AppInfo-${{ github.event.inputs.version }}-source.zip
          path: .

  pack:
    name: Pack NuGet Packages
#    needs: build
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        dotnet-version: [ '10.0.x', '8.0.x' ]

    steps:
      - name: Version
        run: echo "Using version ${{ github.event.inputs.version }}"

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
#          dotnet-version: ${{ matrix.dotnet-version }}
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: >
          dotnet build \
            --no-restore \
            --configuration Release \
            -p:Version="${{ github.event.inputs.version }}"

      - name: Test
        run: >
          dotnet test \
            --no-build \
            --configuration Release \
            --verbosity normal \
            --logger trx \
            --results-directory "TestResults-${{ github.event.inputs.version }}"

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: ${{ always() }}  # Always run this step to publish test results when there are test failures
        with:
#          name: dotnet-results-${{ matrix.dotnet-version }}
#          path: TestResults-${{ matrix.dotnet-version }}
          name: test-results-${{ github.event.inputs.version }}.zip
          path: TestResults-${{ github.event.inputs.version }}

      - name: Create package
        run: >
          dotnet pack \
            "./src/AppInfo/AppInfo.csproj" \
            --nologo \
            --no-build \
            --include-symbols \
            --configuration Release \
            -p:Version="${{ github.event.inputs.version }}" \
            --output "artifacts"

      - name: Upload NuGet to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: "artifacts/*.nupkg"
          archive: false

      - name: Upload symbols to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: "artifacts/*.snupkg"
          archive: false

  publish:
    name: Publish NuGet Packages
    needs: pack
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
      contents: read

    steps:
      - name: Debug
        run: echo "Publishing version: ${{ github.event.inputs.version }} as ${{ secrets.NUGET_USER }}"

      - name: NuGet login  # (OIDC → temp API key)
        uses: NuGet/login@v1  # Get a short-lived NuGet API key
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          environment: "production"

      - name: Publish to NuGet
        if: ${{ !inputs.dry-run }}
        run: dotnet nuget push artifacts/AppInfo.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
