name: Publish NuGet


on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "Version to publish"
      dry-run:
        required: true
        type: boolean
        description: "Dry run (doesn't actually publish anything)"


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Version
        run: echo "vars ${{ vars.VERSION }} env ${{ env.VERSION }} input ${{ github.event.inputs.version }}"

      - name: List
        run: ls -alR

  build:
    name: Build and Test
    uses: ./.github/workflows/ci.yml
    with:
      version: ${{ github.event.inputs.version }}

  zip:
    name: Zip Source Code
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Zip Source Code
        run: |
          mkdir source
          zip -r source/AppInfo-${{ github.event.inputs.version }}-source.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AppInfo-${{ github.event.inputs.version }}
          path: source/

  pack:
    name: Pack NuGet Packages
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    strategy:
      matrix:
        dotnet-version: [ '10.0.x', '8.0.x' ]

    steps:
      - name: Version
        run: echo "Using version ${{ github.event.inputs.version }}"

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: >
          dotnet build \
          --no-restore \
          --configuration Release \
          -p:Version="${{ github.event.inputs.version }}"

      - name: Create package
        run: >
          dotnet pack \
            "./src/AppInfo/AppInfo.csproj" \
            --nologo \
            --no-build \
            --include-symbols \
            --configuration Release \
            -p:Version="${{ github.event.inputs.version }}" \
            --output "artifacts"

      - uses: actions/upload-artifact@v7
        with:
          name: packages
          path: "artifacts"

  publish:
    name: Publish NuGet Packages
    needs: pack

    runs-on: ubuntu-latest

    if: ${{ !inputs.dry-run }}

    steps:
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1  # Get a short-lived NuGet API key
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

#      - name: Publish to NuGet
#        run: dotnet nuget push artifacts/AppInfo.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
